### ISSUE TITLE
Crashes

### ISSUE THREAD

**Issue by maxim3007** [Andereoo/TkinterWeb#15] opened 2021-06-18 19:33 UTC
Hello!
sometimes my tk app crashes due a C assert failure. for example `Assertion failed: (pItem->x.marker.flags), function HtmlDrawCleanup, file ../src/htmldraw.c, line 767.`.
Is it possible to handle asserts and call a function e.g. `HtmlFrame.on_crash` and destroy only frame (not all application)  or to load a blank page?

**Comment by Yilmaz4** [comment] 2021-06-20 09:42
Do you know which line causes the crash? If yes, try to put this line into a `try` `except` statement. If not, I can suggest you to edit the  `/src/htmldraw.c` file and put the 767th line into a `catch` statement to handle exceptions.

**Comment by Andereoo** [comment] 2021-06-20 15:06
@maxim3007 I've encountered this kind of error only twice, when zooming the webpage, but I can't remember exactly what I did to cause the crash. Do you happen to remember what you did that caused Tkinter to crash? If I can reproduce your crashes on my end it will make it a lot easier to troubleshoot and test fixes. Then I can try to handle the errors. @Yilmaz4 thank you for the suggestions. I'll probably have to edit `htmldraw.c` because the error seems to be crashing Tkinter on the Tcl level, not the Python level. Since the error isn't making it's way into Python, I don't think I'll be able to do much on TkinterWeb's end.

**Comment by maxim3007** [comment] 2021-06-20 15:30
The error is raising when I am loading some html from websites by using `load_html`. I. can't use `load_website` because I always need to edit some parts of html programmatically. and yes I am using frame zooming `(zoom=1.4)`. I am going to find what webpage causes my app to crash

**Comment by maxim3007** [comment] 2021-06-20 15:31
And also: maybe it is because some webpages contain non-english characters

**Comment by maxim3007** [comment] 2021-06-20 16:00
I've found a line that causes error `case CANVAS_MARKER:
                assert(pItem->x.marker.flags);
                break;`
and do you know what is `CANVAS_MARKER`. can you try to delete assert statement on line 767??

**Comment by Andereoo** [comment] 2021-06-21 12:18
I doubt that these crashes are an issue with non-English characters, since Tkhtml should be able to handle all characters in Tcl's range. All other characters that might cause issues are stripped out before being sent to the parser (bug #11 ), so we should be good on that front.  Regarding `CANVAS_MARKER`, that constant is defined in line 172: `#define CANVAS_MARKER 7`. I might be able to delete the assert statement, or at least try to validate `pItem` and `x.marker.flags` before running `assert(pItem->x.marker.flags);`. I need to be able to reproduce the crash first, so that I can check that my fixes are working and not causing more issues.

**Comment by maxim3007** [comment] 2021-06-21 15:00
hello,
I still can't find a page that causing an error but maybe you can create a new dir and copy TkinterWeb with changed `htmldraw.c` to it, archive it and maybe send it to this Github chat and I will try to run my app from the folder. (very strange plan but I think it will work)

**Comment by Andereoo** [comment] 2021-06-22 18:09
Hello @maxim3007 @Yilmaz4 I have found some sample sites that cause crashes. Removing the assert statement on line 767 on `htmldraw.c` causes other asserts later in the code to kill the program. Removing all asserts across the Tkhtml3 code base seems to fix all crashes. There is a possibility that this will cause even bigger issues on other websites, so I'm going to keep testing before I release the new binaries.

**Comment by maxim3007** [comment] 2021-06-22 18:22
hello!
is it possible to communicate between C and python??

**Comment by Andereoo** [comment] 2021-06-22 18:55
Hi!

Yes, it is. In this case, Python is communicating with Tcl, which is communicating with C. To send messages back and forth it would be easiest to route the data through Tcl, which would pass it on to C (and vice-versa).

**Comment by Andereoo** [comment] 2021-06-29 19:01
Hi @maxim3007 @Yilmaz4 ,

I have made some changes that should fix these crashes. First of all, all asserts are now ignored. Technically this should have been the standard behavior in the first place. An `if` statement is used on line 767 to catch any errors in a less-invasive way. If an error is encountered, the Python callback script will be invoked. You'll just get a message if this happens (and of course if messages are enabled). If crash prevention is disabled, the code will allow Tkinter to crash. 

So far, these changes are only available on `Windows` and `64-bit Linux`. I'll look into a way to make these fixes available on MacOS, but since I don't have a Mac, compiling Tkhtml for Mac is not exactly straightforward. 

Try going to `finance.yahoo.com` (you may need to zoom the `HtmlFrame`). This used to crash Python, but you will probably see that after updating TkinterWeb now everything works as expected.
 
Hopefully this helps.

**Closed by Andereoo** 2021-06-29 19:01 UTC

**Comment by maxim3007** [comment] 2021-06-29 19:10
Thank you!!

Unfortunately Mac build is not stable at the moment. I hope that you will fix it for mac soon! Again thanks!
